export const LOADING_ERROR = "LOADING_ERROR";
export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
export const LOADING_SUCCESS_HOME = "LOADING_SUCCESS_HOME";
export const LOADING_ID = "LOADING_ID";
export const CLEAR_ALL = "CLEAR_ALL";